# Generated by Django 3.0.5 on 2020-04-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Имя преподавателя')),
                ('phone', models.CharField(max_length=50, verbose_name='Номер')),
                ('telegram', models.CharField(max_length=50, verbose_name='Телеграмм')),
                ('email', models.EmailField(max_length=50, verbose_name='Эмайл')),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
                'ordering': ['name'],
            },
        ),
    ]
