# Generated by Django 3.0.5 on 2020-04-04 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='telegram',
            field=models.CharField(max_length=50, verbose_name='Телеграм'),
        ),
    ]
