# Generated by Django 3.0.5 on 2020-04-03 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('childs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='home_word',
            new_name='homework',
        ),
    ]
