# Generated by Django 3.0.5 on 2020-04-04 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('childs', '0003_auto_20200404_0134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'ordering': ['pk'], 'verbose_name': 'Ученик', 'verbose_name_plural': 'Ученики'},
        ),
    ]
