# Generated by Django 3.0.5 on 2020-04-04 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200404_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='homework',
            field=models.TextField(default='', verbose_name='Домашнее задание'),
            preserve_default=False,
        ),
    ]
